### ISSUE TITLE
Related Project

### ISSUE THREAD

**Issue by tracker1** [mikeobrien/node-sqlcmd-runner#3]
Just created a similar project, but different interface and supports more variety of environments (Windows, Linux, Docker container).  And was wondering if you'd be willing to create a _Related Projects_ section above your license in the readme and linking over.

https://github.com/tracker1/node-ms-sqlcmd

**Comment by mikeobrien** [comment]
Yeah, just submit a PR and I'll accept. I don't use/maintain this anymore so would be great to have an alternative. Thx!

**Comment by mikeobrien** [comment]
Oh and feel free to add it at the top of the readme so people don't miss it.
